### ISSUE TITLE
Character breaks messages

### ISSUE THREAD

**Issue by Nathcat** [Nathcat/PeopleCat-WebAppPrototype#10]
The character `°` is reported to be breaking the message display in the application.

**Comment by Nathcat** [comment]
This is caused by a String encoding error, this is the output from the server when replying to the client with the messages in a chat:
```
----- PACKET JSON DECODE ERROR -----

Culprit String: {"TimeSent":1730425684253,"Content":"￯﾿ﾂ￯ﾾﾰ","SenderID":1,"ChatID

Error:

Unexpected token END OF FILE at position 65.
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:257)
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:81)
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:75)
        at com.nathcat.peoplecat_server.Packet.getData(Packet.java:324)
        at com.nathcat.peoplecat_server.Packet.getData_WebSocket(Packet.java:340)
        at com.nathcat.peoplecat_server.WebSocketOutputStream.write(WebSocketOutputStream.java:57)
        at com.nathcat.peoplecat_server.WebSocketHandler.onMessage(WebSocketHandler.java:146)
        at org.java_websocket.server.WebSocketServer.onWebsocketMessage(WebSocketServer.java:732)
        at org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:986)
        at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:910)
        at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:397)
        at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:229)
        at org.java_websocket.server.WebSocketServer$WebSocketWorker.doDecode(WebSocketServer.java:1134)
        at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:1106)
```

**Comment by Nathcat** [comment]
I'm thinking this might require a major rework in the way that we handle messages. Either a transition from sending `UTF-8` strings to `UTF-16` strings, which as far as I'm aware isn't possible over websockets using the normal string messages.

Perhaps if we used a binary message instead? We could send the whole request in `UTF-16`, but in a binary format, and have it decoded at each end and processed appropriately.

Would probably require a fair bit of work to implement but _should_ theoretically fix this issue.
